### ISSUE TITLE
does ssb-ebt disable the legacy replication?

### ISSUE THREAD

**Issue by christianbundy** [ssbc/ssb-ebt#25]
right now Patchwork has ssb-ebt disabled because of #22, but as long as the legacy replication still works while ssb-ebt is enabled I don't see any reason not to re-enable it

**Comment by dominictarr** [comment]
ebt doesn't disable the legacy replication (unless it's explicitly disabled).
it tries ebt first, then falls back to legacy if there is a error. if it just stalls, that wouldn't happen, so I think we need to either, a) have code that detects the stall and reconnects (ugly hack) or b) actually fix the problem. (needs reproduce code)

**Comment by christianbundy** [comment]
Sweet, thank you for the info!
