### ISSUE TITLE
No matching version found for epidemic-broadcast-trees@^6.3.6

### ISSUE THREAD

**Issue by christianbundy** [ssbc/ssb-ebt#28]
Can't currently install with `npm install`, maybe the package hasn't been published?

cc: @dominictarr

**Comment by christianbundy** [comment]
Also looks like the test have merge commit markers in them currently, maybe a bad merge?

**Comment by dominictarr** [comment]
that should be epidemic-broadcast-trees@7 6.3.6 was an accidential breaking change. it looks like I did publish it on npm as expected, but I think I forgot I wasn't on master branch. fixed in ssb-ebt@5.6.6
