### ISSUE TITLE
console.error is hiding the error details

### ISSUE THREAD

**Issue by staltz** [ssbc/ssb-ebt#49]
```
rpc.ebt.replicate exception: [object Object]
```

**Comment by staltz** [comment]
@arj03 I accidentally just pushed a fix for this to master: https://github.com/ssbc/ssb-ebt/commit/7068abab6b5f5108016ce2299abdbaccc9941791

Next time I'll do a PR

**Comment by arj03** [comment]
no worries, change looks good.
