### ISSUE TITLE
Problems when peer is recovering their feed from zero

### ISSUE THREAD

**Issue by staltz** [ssbc/ssb-ebt#59]
Suppose Alice and Bob are friends and have published a lot of content. Both have ssb-ebt installed, and thus there exists `~/.ssb/ebt/aliceID` on Bob's computer and `~/.ssb/ebt/bobID` on Alice's computer.

If Alice loses her installation and starts from scratch, recovering her `secret` and then reconnecting with Bob, it seems like Bob does not give Alice her feed messages via EBT, when it should. Maybe because of the state persisted on Bob's side, Bob figures that Alice already has all that she needs, when in reality Alice has nothing.

I tested this with a fair amount of confidence (not 100%) by attempting to recover my feed and connecting to N room members. None of the connections gave me my data back.

**Comment by arj03** [comment]
Strange. There should be a [test](https://github.com/ssbc/epidemic-broadcast-trees/blob/bfcd2cab26ecc2a80875dfdcb75fb2e200ce6175/test/lost-state.js#L64) for that in EBT.

**Comment by staltz** [comment]
Maybe something happens on peer close + restart? I think those tests keep all the peers alive and maybe that's different from what I had? I'm not sure, all I know is that I connected to ~6 different room members and nothing was replicating for me at all.

**Comment by staltz** [comment]
I nuked my phone's installation again (this time on purpose) to test whether the recent changes to ssb-db2 would fix this issue. Apparently not. `@+UMK` was connected to `@QlCT` but `@+UMK` didn't get any new data. I tried also removing the ebt file from `@QlCT`'s side and that also didn't have any effect. I ended up connecting to a bunch of other random peers and one of them starting giving me data.

**Comment by mplorentz** [comment]
Huh, I am seeing the same root problem, problems recovering from zero, but with different details.

I am trying to get Planetary/go-ssb to restore an empty profile by syncing with ssb-server. I'm running ssbc/ssb-server commit [919cbdd](https://github.com/ssbc/ssb-server/commit/919cbdd0267b8a5d24923af567390c9b30dae0d3) (head of main), which uses ssb-ebt 5.6.7. If I turn off EBTs and just rely on legacy gossip the whole feed is restored. With EBT replication enabled it seems like ssb-server does not want to send me my own feed. I noticed that the file `~/.ssb/ebt/{my_feed_id}` contains my feed ID and a sequence number greater than 0. Deleting this file doesn't help. Somehow it gets repopulated with the same sequence number that was there before. Where could this sequence number be coming from? Editing the file to set the sequence number for `{my_feed_id}` to 0 results in my client fetching exactly 1 message before getting stuck. Restarting both peers does not cause my client to make any more progress.

**Comment by staltz** [comment]
Oh, this issue should be closed because it's been long since solved, I've tested this use case (restoring feed from scratch) numerous times and the latest versions of ssb-ebt don't have this problem. It seems your issue is with ssb-ebt 5.6.7 that needs to be updated. The latest is ssb-ebt 9.1.0 but ssb-ebt 8.x is also pretty solid (we use it in Manyverse).

**Comment by mplorentz** [comment]
I tested with ssb-ebt 8.2.1 and 9.1.0 but both exhibit the same behavior I am seeing on 5.6.7. I also deleted `~/.ssb/ebt` for good measure.

@staltz do you know which commit or PR fixed this issue for you?

**Comment by staltz** [comment]
I can't at the moment get this information for you because it's Friday evening in my timezone already. Maybe you can figure it out from ssb-ebt commits, epidemic-broadcast-trees commits, and ssb-replication-scheduler. In fact I think ssb-r-s has an integration test specifically covering this issue.

**Comment by mplorentz** [comment]
I will try to read through the commit history at some point, but in the meantime I think there should be an open issue for this somewhere. I'm happy to file a new one here or somewhere else, or we can reopen this one. The issue is easily reproducible with version 16.0.1 of ssb-server, so maybe I should file a ticket in that repo?

**Comment by staltz** [comment]
Perhaps you could start by giving reproduction details and steps so the issue can be reliably experienced on other computers.

**Comment by mplorentz** [comment]
Here is the way I have been reproducing it:
1. Run a pub using ssb-server 15.0.3 or 16.0.1
2. Run Planetary and join the pub
3. Verify that the pub has replicated the Planetary feed
4. Delete the database from Planetary and relaunch
Expected: Planetary connects to the pub and replicates its own feed.
Actual: Planetary connects to the pub and sends EBT notes asking for it's own feed but the pub never sends it.

I realize these steps aren't generic enough, so @mixmix is helping me write a test for this in JS.

As arj mentioned it looks like there already is such a test in https://github.com/ssbc/epidemic-broadcast-trees/blob/bfcd2cab26ecc2a80875dfdcb75fb2e200ce6175/test/lost-state.js#L64 but when I run the tests in that repo it doesn't seem to execute.
